basePath: /
definitions:
  entity.Category:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  entity.Product:
    properties:
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for Go Cashier API.
  title: Go Cashier API
  version: '1.0'
paths:
  /api/categories:
    get:
      consumes:
        - application/json
      description: Get a list of all categories
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Category'
            type: array
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: List all categories
      tags:
        - categories
    post:
      consumes:
        - application/json
      description: Create a new category with the input payload
      parameters:
        - description: Category content
          in: body
          name: category
          required: true
          schema:
            $ref: '#/definitions/entity.Category'
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/entity.Category'
        '400':
          description: Bad Request
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new category
      tags:
        - categories
  /api/categories/{id}:
    delete:
      consumes:
        - application/json
      description: Delete a specific category by its ID
      parameters:
        - description: Category ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Delete a category
      tags:
        - categories
    get:
      consumes:
        - application/json
      description: Get details of a specific category by its ID
      parameters:
        - description: Category ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/entity.Category'
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Get a category by ID
      tags:
        - categories
    put:
      consumes:
        - application/json
      description: Update a specific category by its ID
      parameters:
        - description: Category ID
          in: path
          name: id
          required: true
          type: integer
        - description: Category content
          in: body
          name: category
          required: true
          schema:
            $ref: '#/definitions/entity.Category'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/entity.Category'
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Update a category
      tags:
        - categories
  /api/products:
    get:
      consumes:
        - application/json
      description: Get a list of all products
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Product'
            type: array
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: List all products
      tags:
        - products
    post:
      consumes:
        - application/json
      description: Create a new product with the input payload
      parameters:
        - description: Product content
          in: body
          name: product
          required: true
          schema:
            $ref: '#/definitions/entity.Product'
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/entity.Product'
        '400':
          description: Bad Request
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new product
      tags:
        - products
  /api/products/{id}:
    delete:
      consumes:
        - application/json
      description: Delete a specific product by its ID
      parameters:
        - description: Product ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Delete a product
      tags:
        - products
    get:
      consumes:
        - application/json
      description: Get details of a specific product by its ID
      parameters:
        - description: Product ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/entity.Product'
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Get a product by ID
      tags:
        - products
    put:
      consumes:
        - application/json
      description: Update a specific product by its ID
      parameters:
        - description: Product ID
          in: path
          name: id
          required: true
          type: integer
        - description: Product content
          in: body
          name: product
          required: true
          schema:
            $ref: '#/definitions/entity.Product'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/entity.Product'
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Update a product
      tags:
        - products
swagger: '2.0'
